// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgHeader.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_MsgHeader_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_MsgHeader_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3013000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3013000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_MsgHeader_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_MsgHeader_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MsgHeader_2eproto;
namespace Serialize {
class MsgHeaderProto;
class MsgHeaderProtoDefaultTypeInternal;
extern MsgHeaderProtoDefaultTypeInternal _MsgHeaderProto_default_instance_;
}  // namespace Serialize
PROTOBUF_NAMESPACE_OPEN
template<> ::Serialize::MsgHeaderProto* Arena::CreateMaybeMessage<::Serialize::MsgHeaderProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Serialize {

// ===================================================================

class MsgHeaderProto PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Serialize.MsgHeaderProto) */ {
 public:
  inline MsgHeaderProto() : MsgHeaderProto(nullptr) {}
  virtual ~MsgHeaderProto();

  MsgHeaderProto(const MsgHeaderProto& from);
  MsgHeaderProto(MsgHeaderProto&& from) noexcept
    : MsgHeaderProto() {
    *this = ::std::move(from);
  }

  inline MsgHeaderProto& operator=(const MsgHeaderProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline MsgHeaderProto& operator=(MsgHeaderProto&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MsgHeaderProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MsgHeaderProto* internal_default_instance() {
    return reinterpret_cast<const MsgHeaderProto*>(
               &_MsgHeaderProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MsgHeaderProto& a, MsgHeaderProto& b) {
    a.Swap(&b);
  }
  inline void Swap(MsgHeaderProto* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MsgHeaderProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MsgHeaderProto* New() const final {
    return CreateMaybeMessage<MsgHeaderProto>(nullptr);
  }

  MsgHeaderProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MsgHeaderProto>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MsgHeaderProto& from);
  void MergeFrom(const MsgHeaderProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgHeaderProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Serialize.MsgHeaderProto";
  }
  protected:
  explicit MsgHeaderProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_MsgHeader_2eproto);
    return ::descriptor_table_MsgHeader_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMToFieldNumber = 1,
    kMFromFieldNumber = 2,
    kMTypeFieldNumber = 3,
    kMSizeFieldNumber = 4,
  };
  // string m_To = 1;
  void clear_m_to();
  const std::string& m_to() const;
  void set_m_to(const std::string& value);
  void set_m_to(std::string&& value);
  void set_m_to(const char* value);
  void set_m_to(const char* value, size_t size);
  std::string* mutable_m_to();
  std::string* release_m_to();
  void set_allocated_m_to(std::string* m_to);
  private:
  const std::string& _internal_m_to() const;
  void _internal_set_m_to(const std::string& value);
  std::string* _internal_mutable_m_to();
  public:

  // string m_From = 2;
  void clear_m_from();
  const std::string& m_from() const;
  void set_m_from(const std::string& value);
  void set_m_from(std::string&& value);
  void set_m_from(const char* value);
  void set_m_from(const char* value, size_t size);
  std::string* mutable_m_from();
  std::string* release_m_from();
  void set_allocated_m_from(std::string* m_from);
  private:
  const std::string& _internal_m_from() const;
  void _internal_set_m_from(const std::string& value);
  std::string* _internal_mutable_m_from();
  public:

  // int32 m_Type = 3;
  void clear_m_type();
  ::PROTOBUF_NAMESPACE_ID::int32 m_type() const;
  void set_m_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_m_type() const;
  void _internal_set_m_type(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 m_Size = 4;
  void clear_m_size();
  ::PROTOBUF_NAMESPACE_ID::int32 m_size() const;
  void set_m_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_m_size() const;
  void _internal_set_m_size(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Serialize.MsgHeaderProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr m_to_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr m_from_;
  ::PROTOBUF_NAMESPACE_ID::int32 m_type_;
  ::PROTOBUF_NAMESPACE_ID::int32 m_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_MsgHeader_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MsgHeaderProto

// string m_To = 1;
inline void MsgHeaderProto::clear_m_to() {
  m_to_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& MsgHeaderProto::m_to() const {
  // @@protoc_insertion_point(field_get:Serialize.MsgHeaderProto.m_To)
  return _internal_m_to();
}
inline void MsgHeaderProto::set_m_to(const std::string& value) {
  _internal_set_m_to(value);
  // @@protoc_insertion_point(field_set:Serialize.MsgHeaderProto.m_To)
}
inline std::string* MsgHeaderProto::mutable_m_to() {
  // @@protoc_insertion_point(field_mutable:Serialize.MsgHeaderProto.m_To)
  return _internal_mutable_m_to();
}
inline const std::string& MsgHeaderProto::_internal_m_to() const {
  return m_to_.Get();
}
inline void MsgHeaderProto::_internal_set_m_to(const std::string& value) {
  
  m_to_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MsgHeaderProto::set_m_to(std::string&& value) {
  
  m_to_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Serialize.MsgHeaderProto.m_To)
}
inline void MsgHeaderProto::set_m_to(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  m_to_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:Serialize.MsgHeaderProto.m_To)
}
inline void MsgHeaderProto::set_m_to(const char* value,
    size_t size) {
  
  m_to_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Serialize.MsgHeaderProto.m_To)
}
inline std::string* MsgHeaderProto::_internal_mutable_m_to() {
  
  return m_to_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MsgHeaderProto::release_m_to() {
  // @@protoc_insertion_point(field_release:Serialize.MsgHeaderProto.m_To)
  return m_to_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MsgHeaderProto::set_allocated_m_to(std::string* m_to) {
  if (m_to != nullptr) {
    
  } else {
    
  }
  m_to_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), m_to,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Serialize.MsgHeaderProto.m_To)
}

// string m_From = 2;
inline void MsgHeaderProto::clear_m_from() {
  m_from_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& MsgHeaderProto::m_from() const {
  // @@protoc_insertion_point(field_get:Serialize.MsgHeaderProto.m_From)
  return _internal_m_from();
}
inline void MsgHeaderProto::set_m_from(const std::string& value) {
  _internal_set_m_from(value);
  // @@protoc_insertion_point(field_set:Serialize.MsgHeaderProto.m_From)
}
inline std::string* MsgHeaderProto::mutable_m_from() {
  // @@protoc_insertion_point(field_mutable:Serialize.MsgHeaderProto.m_From)
  return _internal_mutable_m_from();
}
inline const std::string& MsgHeaderProto::_internal_m_from() const {
  return m_from_.Get();
}
inline void MsgHeaderProto::_internal_set_m_from(const std::string& value) {
  
  m_from_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void MsgHeaderProto::set_m_from(std::string&& value) {
  
  m_from_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:Serialize.MsgHeaderProto.m_From)
}
inline void MsgHeaderProto::set_m_from(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  m_from_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:Serialize.MsgHeaderProto.m_From)
}
inline void MsgHeaderProto::set_m_from(const char* value,
    size_t size) {
  
  m_from_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:Serialize.MsgHeaderProto.m_From)
}
inline std::string* MsgHeaderProto::_internal_mutable_m_from() {
  
  return m_from_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* MsgHeaderProto::release_m_from() {
  // @@protoc_insertion_point(field_release:Serialize.MsgHeaderProto.m_From)
  return m_from_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MsgHeaderProto::set_allocated_m_from(std::string* m_from) {
  if (m_from != nullptr) {
    
  } else {
    
  }
  m_from_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), m_from,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:Serialize.MsgHeaderProto.m_From)
}

// int32 m_Type = 3;
inline void MsgHeaderProto::clear_m_type() {
  m_type_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgHeaderProto::_internal_m_type() const {
  return m_type_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgHeaderProto::m_type() const {
  // @@protoc_insertion_point(field_get:Serialize.MsgHeaderProto.m_Type)
  return _internal_m_type();
}
inline void MsgHeaderProto::_internal_set_m_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  m_type_ = value;
}
inline void MsgHeaderProto::set_m_type(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_m_type(value);
  // @@protoc_insertion_point(field_set:Serialize.MsgHeaderProto.m_Type)
}

// int32 m_Size = 4;
inline void MsgHeaderProto::clear_m_size() {
  m_size_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgHeaderProto::_internal_m_size() const {
  return m_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgHeaderProto::m_size() const {
  // @@protoc_insertion_point(field_get:Serialize.MsgHeaderProto.m_Size)
  return _internal_m_size();
}
inline void MsgHeaderProto::_internal_set_m_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  m_size_ = value;
}
inline void MsgHeaderProto::set_m_size(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_m_size(value);
  // @@protoc_insertion_point(field_set:Serialize.MsgHeaderProto.m_Size)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Serialize

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_MsgHeader_2eproto
