// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MsgHeader.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
using System;
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Serialize {

  /// <summary>Holder for reflection information generated from MsgHeader.proto</summary>
  public static partial class MsgHeaderReflection {

    #region Descriptor
    /// <summary>File descriptor for MsgHeader.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgHeaderReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9Nc2dIZWFkZXIucHJvdG8SCVNlcmlhbGl6ZSJOCg5Nc2dIZWFkZXJQcm90",
            "bxIMCgRtX1RvGAEgASgJEg4KBm1fRnJvbRgCIAEoCRIOCgZtX1R5cGUYAyAB",
            "KAUSDgoGbV9TaXplGAQgASgFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Serialize.MsgHeaderProto), global::Serialize.MsgHeaderProto.Parser, new[]{ "MTo", "MFrom", "MType", "MSize" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MsgHeaderProto : pb::IMessage<MsgHeaderProto>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgHeaderProto> _parser = new pb::MessageParser<MsgHeaderProto>(() => new MsgHeaderProto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MsgHeaderProto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Serialize.MsgHeaderReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgHeaderProto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgHeaderProto(MsgHeaderProto other) : this() {
      mTo_ = other.mTo_;
      mFrom_ = other.mFrom_;
      mType_ = other.mType_;
      mSize_ = other.mSize_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MsgHeaderProto Clone() {
      return new MsgHeaderProto(this);
    }

    /// <summary>Field number for the "m_To" field.</summary>
    public const int MToFieldNumber = 1;
    private string mTo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MTo {
      get { return mTo_; }
      set {
        mTo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "m_From" field.</summary>
    public const int MFromFieldNumber = 2;
    private string mFrom_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MFrom {
      get { return mFrom_; }
      set {
        mFrom_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "m_Type" field.</summary>
    public const int MTypeFieldNumber = 3;
    private int mType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MType {
      get { return mType_; }
      set {
        mType_ = value;
      }
    }

    /// <summary>Field number for the "m_Size" field.</summary>
    public const int MSizeFieldNumber = 4;
    private int mSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MSize {
      get { return mSize_; }
      set {
        mSize_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MsgHeaderProto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MsgHeaderProto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MTo != other.MTo) return false;
      if (MFrom != other.MFrom) return false;
      if (MType != other.MType) return false;
      if (MSize != other.MSize) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MTo.Length != 0) hash ^= MTo.GetHashCode();
      if (MFrom.Length != 0) hash ^= MFrom.GetHashCode();
      if (MType != 0) hash ^= MType.GetHashCode();
      if (MSize != 0) hash ^= MSize.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MTo.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MTo);
      }
      if (MFrom.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MFrom);
      }
      if (MType != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MType);
      }
      if (MSize != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(MSize);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MTo.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(MTo);
      }
      if (MFrom.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MFrom);
      }
      if (MType != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MType);
      }
      if (MSize != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(MSize);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MTo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MTo);
      }
      if (MFrom.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MFrom);
      }
      if (MType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MType);
      }
      if (MSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MSize);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MsgHeaderProto other) {
      if (other == null) {
        return;
      }
      if (other.MTo.Length != 0) {
        MTo = other.MTo;
      }
      if (other.MFrom.Length != 0) {
        MFrom = other.MFrom;
      }
      if (other.MType != 0) {
        MType = other.MType;
      }
      if (other.MSize != 0) {
        MSize = other.MSize;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MTo = input.ReadString();
            break;
          }
          case 18: {
            MFrom = input.ReadString();
            break;
          }
          case 24: {
            MType = input.ReadInt32();
            break;
          }
          case 32: {
            MSize = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MTo = input.ReadString();
            break;
          }
          case 18: {
            MFrom = input.ReadString();
            break;
          }
          case 24: {
            MType = input.ReadInt32();
            break;
          }
          case 32: {
            MSize = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
